### ISSUE TITLE
Minimum height? 

### ISSUE THREAD

**Issue by BitPopCoin** [ornj/seamless-polyfill#5]
I'd like to set a minimum height, is it possible?

**Comment by ornj** [comment]
Not through the script, although that logic could easily be added. For the time being you could set a minimum height in your CSS.

``` css
iframe {
    min-height: 250px;
}
```

That should override the inline height attribute if it's smaller than your minimum.
